version: '3.8'
services:
  nano:
    container_name: Nano
    image: theprogrammershangout/nano:latest
    volumes:
      - type: bind
        source: ./config
        target: /config
    restart: always
    env_file:
      - .env